### ISSUE TITLE
Be able to select openstack networks

### ISSUE THREAD

**Issue by mhpx** [hep-gc/cloud-scheduler#354]
clouds with multiple networks require one to be specified during vm creation and cannot rely on default

**Comment by berghaus** [comment]
Not sure if this relates but CS crashed with this (on the instance at UVic):

```
Traceback (most recent call last):
  File "/usr/local/bin/cloud_scheduler", line 5, in <module>
    pkg_resources.run_script('cloud-scheduler==1.8', 'cloud_scheduler')
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 489, in run_script
  File "/usr/local/lib/python2.7/site-packages/setuptools-0.6c11-py2.7.egg/pkg_resources.py", line 1207, in run_script
  File "/usr/local/lib/python2.7/site-packages/cloud_scheduler-1.8-py2.7.egg/EGG-INFO/scripts/cloud_scheduler", line 2362, in <module>
    main()
  File "/usr/local/lib/python2.7/site-packages/cloud_scheduler-1.8-py2.7.egg/EGG-INFO/scripts/cloud_scheduler", line 2163, in main
    cloud_resources = cloud_management.ResourcePool(config.cloud_resource_config)
  File "/usr/local/lib/python2.7/site-packages/cloud_scheduler-1.8-py2.7.egg/cloudscheduler/cloud_management.py", line 147, in __init__
    self.setup()
  File "/usr/local/lib/python2.7/site-packages/cloud_scheduler-1.8-py2.7.egg/cloudscheduler/cloud_management.py", line 184, in setup
    new_cluster = self._cluster_from_config(cloud_config, cluster)
  File "/usr/local/lib/python2.7/site-packages/cloud_scheduler-1.8-py2.7.egg/cloudscheduler/cloud_management.py", line 413, in _cluster_from_config
    networks = splitnstrip(",", get_or_none(config, cluster, "networks")),
  File "/usr/local/lib/python2.7/site-packages/cloud_scheduler-1.8-py2.7.egg/cloudscheduler/utilities.py", line 66, in splitnstrip
    return [x.strip() for x in val.split(sep)];
AttributeError: 'NoneType' object has no attribute 'split'
```

It crashed at 16:25pm PST yesterday and I restarted it today at 5:15am PST today.

**Comment by mhpx** [comment]
Looks like there's a small bug that requires the "networks" field be in 
the cloud_resources even if it's empty.

**Comment by mhpx** [comment]
related commit - https://github.com/hep-gc/cloud-scheduler/commit/0d1ef465df28b47563dd8206adf7392713aed352?diff=unified 
this should allow networks to be left out of the cloud_resources.conf
