### ISSUE TITLE
GCE Issue When Starting Cloud Scheduler

### ISSUE THREAD

**Issue by rd37** [hep-gc/cloud-scheduler#385]
Google Module Complains on cloudscheduler start

/usr/lib/python2.7/site-packages/novaclient/v1_1/__init__.py:30: UserWarning: Module novaclient.v1_1 is deprecated (taken as a basis for novaclient.v2). The preferable way to get client class or object you can find in novaclient.client module.
  warnings.warn("Module novaclient.v1_1 is deprecated (taken as a basis for "
Traceback (most recent call last):
  File "./cloud_scheduler", line 2411, in <module>
    main()
  File "./cloud_scheduler", line 2212, in main
    cloud_resources = cloud_management.ResourcePool(config.cloud_resource_config)
  File "/root/cloud-scheduler/cloudscheduler/cloud_management.py", line 148, in __init__
    self.setup()
  File "/root/cloud-scheduler/cloudscheduler/cloud_management.py", line 185, in setup
    new_cluster = self._cluster_from_config(cloud_config, cluster)
  File "/root/cloud-scheduler/cloudscheduler/cloud_management.py", line 412, in _cluster_from_config
    total_cpu_cores = total_cpu_cores,
  File "/root/cloud-scheduler/cloudscheduler/googlecluster.py", line 69, in __init__
    flow = flow_from_clientsecrets(self.secret_file_path, scope=self.GCE_SCOPE)
NameError: global name 'flow_from_clientsecrets' is not defined

-- seems to be missing flow_from_cloudsecrets function ....

**Comment by mhpx** [comment]
is the oauth2client module installed?
