### ISSUE TITLE
CS hits open file limit

### ISSUE THREAD

**Issue by rptaylor** [hep-gc/cloud-scheduler#387]
2015-08-19 10:42:12,755 - ERROR - JobPoller - Problem running condor_q -l, unexpected error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cloudscheduler/job_management.py", line 522, in job_query_local
    stdout=subprocess.PIPE, stderr=subprocess.PIPE)
  File "/usr/local/lib/python2.7/subprocess.py", line 665, in **init**
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "/usr/local/lib/python2.7/subprocess.py", line 1030, in _get_handles
    c2pread, c2pwrite = os.pipe()
OSError: [Errno 24] Too many open files 

I think the best way to handle this is probably doing "ulimit -n 8000" (or some large number) in the CS init script.

**Comment by rptaylor** [comment]
As a temporary workaround on condor.heprc I created /etc/security/limits.d/99-root-files.conf .
TODO: it should be removed once a permanent solution is in place.

**Comment by rptaylor** [comment]
An alternative approach would be for the CS RPM to provide a file such as /etc/security/limits.d/99-root-files.conf. I think the filename has to be alphanumerically after 90-nproc.conf.

I think the limits.d/ way may not apply on processes initialized at system startup, so this method would be ineffective. However I think this depends on what user the process runs as (i.e. if a PAM-enabled session is started) and it may have changed in RHEL6 vs RHEL5.

So probably the surest way is to do ulimit in the init script, although it isn't as seemly.
