### ISSUE TITLE
Reason: __init__() got an unexpected keyword argument 'cacert'

### ISSUE THREAD

**Issue by evamvak** [hep-gc/cloud-scheduler#405]
Dear developers

last snap of cloud-scheduler from git failed with 

2015-10-08 14:31:43,757 - DEBUG - JobPoller - vamvakop:ccvmwn vmtype added to required types
2015-10-08 14:31:48,323 - DEBUG - Scheduler - CLUSTER Name: cloud_atlas_test, Address: https://cckeystone.in2p3.fr:35357/v2.0/, Type: OpenStackNative, VM slots: 1, Mem: [20000]
2015-10-08 14:31:48,327 - DEBUG - Scheduler - Booting VM for job ccwlcgatlas05.in2p3.fr#77.63#1444299925 on: cloud_atlas_test
2015-10-08 14:31:48,327 - DEBUG - Scheduler - CLUSTER Name: cloud_atlas_test, Address: https://cckeystone.in2p3.fr:35357/v2.0/, Type: OpenStackNative, VM slots: 1, Mem: [20000]
2015-10-08 14:31:48,328 - ERROR - Scheduler - Unable to create connection to cloud_atlas_test: Reason: __init__() got an unexpected keyword argument 'cacert'
Exception in thread Scheduler:
Traceback (most recent call last):
  File "/usr/lib64/python2.6/threading.py", line 532, in __bootstrap_inner
    self.run()
  File "../cloud_scheduler", line 349, in run
    self.scheduling_method()
  File "../cloud_scheduler", line 568, in scheduler_fair_share
    if self.sched_resource_create_track(user, job):
  File "../cloud_scheduler", line 649, in sched_resource_create_track
    create_ret = self.vm_creation(job, good_resources)
  File "../cloud_scheduler", line 872, in vm_creation
    create_ret = resource.vm_create(**args)
  File "/opt/cloud-scheduler/cloudscheduler/openstackcluster.py", line 86, in vm_create
    nova = self._get_creds_nova()
  File "/opt/cloud-scheduler/cloudscheduler/openstackcluster.py", line 306, in _get_creds_nova
    return client
UnboundLocalError: local variable 'client' referenced before assignment

I have define the cacert full path in cloud resources file 
I use python 2.6 on SL6 with 
python-novaclient-2.10.0-2.el6.noarch
any idea ? 
best 
e.v.

**Comment by mhpx** [comment]
which version of the python-novaclient module do you have installed?  We had some problems with the latest 2.30+ versions that have not been resolved yet. (version 2.27, and 2.28.2 seem to work)
can check by running python:
import novaclient
novaclient.__version__

**Comment by mhpx** [comment]
I missed you already said the version of novaclient at the end. Try updating to one of the above.

**Comment by evamvak** [comment]
Ok thanks 
my version is 
>>> import novaclient
>>> novaclient.__version__
'2.10.0'
I will the working ones 
thanks 
best
e.v.
