### ISSUE TITLE
Hold job with reason when unable to fetch image.

### ISSUE THREAD

**Issue by crlb** [hep-gc/cloud-scheduler#411]
Currently, only the cloud scheduler log file identifies this error. Symptoms from the log file are as follows:

2015-10-27 08:22:37,064 - DEBUG - Scheduler - Using security group: ['default']
2015-10-27 08:22:37,360 - WARNING - Scheduler - Exception occurred while trying to fetch image via name: publicURL endpoint for compute service in nova region not found
2015-10-27 08:22:37,362 - ERROR - Scheduler - Unable to fetch image via uuid: publicURL endpoint for compute service in nova region not found
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cloud_scheduler-1.10-py2.7.egg/cloudscheduler/openstackcluster.py", line 159, in vm_create
    imageobj = nova.images.get(image)
  File "/usr/local/lib/python2.7/site-packages/novaclient/v2/images.py", line 53, in get
    return self._get("/images/%s" % base.getid(image), "image")
  File "/usr/local/lib/python2.7/site-packages/novaclient/base.py", line 164, in _get
    _resp, body = self.api.client.get(url)
  File "/usr/local/lib/python2.7/site-packages/keystoneclient/adapter.py", line 170, in get
    return self.request(url, 'GET', **kwargs)
  File "/usr/local/lib/python2.7/site-packages/novaclient/client.py", line 90, in request
    **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keystoneclient/adapter.py", line 206, in request
    resp = super(LegacyJsonAdapter, self).request(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keystoneclient/adapter.py", line 95, in request
    return self.session.request(url, method, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keystoneclient/utils.py", line 337, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keystoneclient/session.py", line 325, in request
    base_url = self.get_endpoint(auth, **endpoint_filter)
  File "/usr/local/lib/python2.7/site-packages/keystoneclient/session.py", line 660, in get_endpoint
    return auth.get_endpoint(self, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keystoneclient/auth/identity/base.py", line 319, in get_endpoint
    service_name=service_name)
  File "/usr/local/lib/python2.7/site-packages/keystoneclient/utils.py", line 337, in inner
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/keystoneclient/service_catalog.py", line 293, in url_for
    raise exceptions.EndpointNotFound(msg)
EndpointNotFound: publicURL endpoint for compute service in nova region not found
2015-10-27 08:22:37,365 - DEBUG - Scheduler - Creating VM for job gcecs.heprc.uvic.ca#40383.0#1445959215 failed on alto. 
2015-10-27 08:22:37,366 - DEBUG - Scheduler - None of the resources could boot a vm for job gcecs.heprc.uvic.ca#40383.0#1445959215. Leaving crlb's job unscheduled.

**Comment by mhpx** [comment]
re-download the openrc.sh file and check that region is correctly configured in the cloud_resources.conf for the Alto cloud.
