### ISSUE TITLE
problem with old job tracking code

### ISSUE THREAD

**Issue by mhpx** [hep-gc/cloud-scheduler#481]
2018-01-27 08:38:28,257 - ERROR - JobPoller - Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/cloud_scheduler-1.13-py2.7.egg/EGG-INFO/scripts/cloud_scheduler", line 227, in run
    self.job_pool.update_jobs(condor_jobs)
  File "/usr/local/lib/python2.7/site-packages/cloud_scheduler-1.13-py2.7.egg/cloudscheduler/job_management.py", line 664, in update_jobs
    self.track_run_time(removed)
  File "/usr/local/lib/python2.7/site-packages/cloud_scheduler-1.13-py2.7.egg/cloudscheduler/job_management.py", line 1117, in track_run_time
    job.running_vm.job_run_times.append(int(job.servertime) - int(job.jobstarttime))
\AttributeError: JobRunTrackQueue instance has no attribute 'append'
2018-01-27 08:38:28,412 - ERROR - MainThread - JobPoller thread died!

**Comment by mhpx** [comment]
https://github.com/hep-gc/cloud-scheduler/commit/daa6af1d08102cce9eb5b306202efc4e0b97b0d2
